#! /bin/bash

#apt-get install unattended-upgrades; dpkg-reconfigure unattended-upgrades
#echo -e "APT::Periodic::Update-Package-Lists \"1\";\nAPT::Periodic::Download-Upgradeable-Packages \"1\";\nAPT::Periodic::AutocleanInterval\"7\";\nAPT::Periodic::Unattended-Upgrade\"1\";\nAPT::Periodic::RandomSleep\"1\";" > /etc/apt/apt.conf.d/10periodic; echo -e "APT::Periodic::Update-Package-Lists \"1\";\nAPT::Periodic::Download-Upgradeable-Packages \"1\";\nAPT::Periodic::AutocleanInterval\"7\";\nAPT::Periodic::Unattended-Upgrade\"1\";\nAPT::Periodic::RandomSleep\"1\";" > /etc/apt/apt.conf.d/20auto-upgrades; echo -e "Unattended-Upgrade::Allowed-Origins {\n	\"\${distro_id}:\${distro_codename}\";\n	\"\${distro_id}:\${distro_codename}-security\";\n	\"\${distro_id}:\${distro_codename}-updates\";\n	\"\${distro_id}:\${distro_codename}-proposed\";\n};\nUnattended-Upgrade::Package-Blacklist {\n};\nUnattended-Upgrade::AutoFixInterruptedDpkg \"false\";\nUnattended-Upgrade::Automatic-Reboot \"true\";\nUnattended-Upgrade::Automatic-Reboot-Time \"03:30\";" > /etc/apt/apt.conf.d/50unattended-upgrades
#echo "Which version of Ubuntu are you on? If you do not wish to update the sources.list, select \"nopatch\""
#select askUbuntuVersion in "Precise" "Trusty" "Xenial" "Debian" "nopatch"; do
#	case $askUbuntuVersion in
#		Precise )	echo -e "deb http://us.archive.ubuntu.com/ubuntu/ precise main restricted universe\ndeb-src http://us.archive.ubuntu.com/ubuntu/ precise main restricted universe multiverse\ndeb http://us.archive.ubuntu.com/ubuntu/ precise-security main restricted universe\ndeb http://us.archive.ubuntu.com/ubuntu/ precise-updates main restricted universe\ndeb http://us.archive.ubuntu.com/ubuntu/ precise-proposed main restricted universe\ndeb-src http://us.archive.ubuntu.com/ubuntu/ precise-security main restricted universe multiverse\ndeb-src http://us.archive.ubuntu.com/ubuntu/ precise-updates main restricted universe multiverse\ndeb-src http://us.archive.ubuntu.com/ubuntu/ precise-proposed main restricted universe multiverse\ndeb-src http://us.archive.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse" > /etc/apt/sources.list; break;;
#		Trusty  ) 	echo -e "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe\ndeb-src http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse\ndeb http://us.archive.ubuntu.com/ubuntu/ trusty-security main restricted universe\ndeb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe\ndeb http://us.archive.ubuntu.com/ubuntu/ trusty-proposed main restricted universe\ndeb-src http://us.archive.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse\ndeb-src http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse\ndeb-src http://us.archive.ubuntu.com/ubuntu/ trusty-proposed main restricted universe multiverse\ndeb-src http://us.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse" > /etc/apt/sources.list; break;;
#		Xenial  ) 	echo -e "deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted universe\ndeb-src http://us.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse\ndeb http://us.archive.ubuntu.com/ubuntu/ xenial-security main restricted universe\ndeb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe\ndeb http://us.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted universe\ndeb-src http://us.archive.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse\ndeb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse\ndeb-src http://us.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted universe multiverse\ndeb-src http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse " > /etc/apt/sources.list; break;;
#		Debian  )   echo -e "deb http://ftp.us.debian.org/debian/ jessie main contrib non-free\ndeb-src http://ftp.us.debian.org/debian/ jessie main contrib non-free\ndeb http://security.debian.org/ jessie/updates main contrib non-free\ndeb http://ftp.us.debian.org/debian/ jessie-proposed-updates main contrib non-free\ndeb-src http://security.debian.org/ jessie/updates main contrib non-free\ndeb-src http://ftp.us.debian.org/debian/ jessie-proposed-updates main contrib non-free" > /etc/apt/sources.list; break;;
#		nopatch ) 	echo -e "Not updating sources.list"; break;;
#	esac
#done
#read -p "Press Enter to Continue. You should have edited the sources.list already with the above. If not, do so now. " continuego
#apt-get update
#apt-get dist-upgrade
#apt-get autoremove

echo "THIS SCRIPT IS IN SAFE MODE. UNCOMMENT TO ENABLE."
